### ISSUE TITLE
Code using manual file operations instead of a context manager

### ISSUE THREAD

**Issue by ghost** [27m/nftlistmaker#1]
When working with files I recommend using a context manager instead of just opening the file with the `open()` function.
### Instead of:
```py  
file = open("nftlist.txt", "w")
file.write(", ".join(nftlist))
```

### Use something like:
```py
with open("nftlist.txt", "w") as file:
  file.write(", ".join(nftlist))
```

This context manager automatically closes the file for you instead of having to to do that yourself. It also makes your code look a lot more intuitive.

**Comment by ghost** [comment]
I hope this helps

**Comment by 27m** [comment]
Thanks 9ggy! always open to suggestions, will add this.

**Comment by 27m** [comment]
solved
